const REGISTRATION_FORM_URL = 'https://docs.google.com/forms/d/1Ex7xuNwvvoy_Opl0pMBO9VIr5lQVeRQuEB7ZPolhJXU/viewform';
const people = {
 'Kyung-Sup Chang':{photo:'photos/kyungsup-chang.jpg',bio:"SNU Distinguished Professor of Sociology. His work covers compressed modernity, comparative citizenship regimes, development politics and transnational Asianization."},
 'Diana Panke':{photo:'photos/Photo_Diana%20Panke.jpeg',bio:"Professor for International Relations at Freie Universität Berlin; Director for Career Development at SCRIPTS and Dean of Research. Her work focuses on international organizations, global governance, norms, negotiations, and comparative regionalism."},
 'Tanja A. Börzel':{photo:'photos/Photo_Tanja%20A.%20B%C3%B6rzel.jpg',bio:"Professor of Political Science at Freie Universität Berlin, Director of SCRIPTS, and Dean of the Department of Political and Social Sciences. Her research focuses on the resilience of liberal orders."},
 'Jeong-Woo Koo':{photo:'photos/jeongwoo-koo.png',bio:"Professor of Sociology at Sungkyunkwan University and Director of the Sungkyunkwan Center for Human Rights and Development. His research includes global sociology, human rights, digital sociology, and corporate social responsibility."},
 'Yasemin Soysal':{photo:'photos/Photo_Yasemin%20Soysal.jpg',bio:"Research Professor of Global Sociology at the Berlin Social Science Center and University Professor at Freie Universität Berlin. She is Co-Deputy Director of SCRIPTS and studies climate skepticism, science ethics, and epistemic contestations."},
 'Dong-Kyun Im':{photo:'photos/dongkyun-im.png',bio:"Professor of Sociology at Seoul National University and Director of the Institute for Social Development and Policy Research. His research explores inequality, welfare, digital citizenship, artificial intelligence, and social trust."},
 'Jieun Kim':{photo:'photos/jieun-kim.jpg',bio:"Assistant Professor of Political Science and International Relations at Seoul National University. Her research examines comparative and Chinese politics, authoritarian institutions, and state–society relations."},
 'Mark Hallerberg':{photo:'photos/Photo_Mark%20Hallerberg.jpg',bio:"Dean of Research and Faculty and Professor of Public Management and Political Economy at the Hertie School. He is also Co-Deputy Director of SCRIPTS; his research focuses on fiscal governance and economic policy."},
 'Chungshik Moon':{photo:'photos/chungshik-moon.jpg',bio:"Professor of Political Science and International Relations at Chung-Ang University. His research focuses on international and comparative political economy, FDI, ODA, authoritarian institutions, and the shadow economy."},
 'Taesuh Cha':{photo:'photos/taesuh-cha.jpg',bio:"Associate Professor of Political Science and International Relations at Seoul National University. He specializes in U.S. foreign policy, international relations theory, and the history of international relations."},
 'Soo Yeon Kim':{photo:'photos/soo-yeon-kim.jpg',bio:"Associate Professor in the School of Public Policy and Global Affairs, Editor of Pacific Affairs, and Korea Foundation Chair at the University of British Columbia. Her research focuses on international political economy and trade politics."},
 'Brandon Ives':{photo:'photos/brandon-ives.jpg',bio:"Associate Professor of Political Science and International Relations at Seoul National University. His research spans violent and nonviolent civil conflict, political behavior, conflict and health, and repression and dissent."},
 'Yoonsun Han':{photo:'photos/yoonsun-han.png',bio:"Associate Professor in the Department of Social Welfare at Seoul National University. Her research centers on child and youth welfare, social protection systems, and the integration of youth with immigrant backgrounds."},
 'Gülay Çağlar':{photo:'photos/Photo_G%C3%BClay%20%C3%87a%C4%9Flar.jpg',bio:"Professor of Political Science at Freie Universität Berlin and Head of Internationalization for SCRIPTS. Her work focuses on international organizations, transnational feminisms, cyberviolence, gender and diversity, intersectionality, and feminist political ecology."},
 'Inbok Rhee':{photo:'photos/Photo_Inbok%20Rhee.jpg',bio:"Biography to be announced."},
 'Min Hee Go':{photo:'photos/minhee-go.jpg',bio:"Professor of Political Science and International Relations at Ewha Womans University, Chief Communications Officer, and Director of the Ewha Institute of Politics. Her research examines social minorities in democratic politics."},
 'Sung Eun Kim':{photo:'photos/sungeun-kim.png',bio:"Professor of Political Science and International Relations at Korea University. Her research focuses on international political economy, trade, China’s foreign economic strategies, foreign aid, and environmental politics."},
 'Joonseok Yang':{photo:'photos/joonseok-yang.jpg',bio:"Assistant Professor of Political Science and International Relations at Yonsei University. His research focuses on trade and investment, environmental politics, energy policy, and foreign aid."},
 'Genia Kostka':{photo:'photos/Photo_Genia%20Kostka.jpg',bio:"Professor of Chinese Politics at Freie Universität Berlin and Principal Investigator at SCRIPTS. Her research focuses on digital governance, emerging technologies, and environmental politics in China."},
 'ByungKoo Kim':{photo:'photos/byungkoo-kim.png',bio:"Assistant Professor of Data Science at the KDI School of Public Policy and Management. His research lies at the intersection of international political economy and quantitative methods."},
 'One-Sun Cho':{photo:'photos/onesun-cho.jpg',bio:"Associate Research Fellow at the Science and Technology Policy Institute and Adjunct Professor at Hanyang University. His research focuses on economic security, cybersecurity, and technology and international relations."},
 'Seungjun Kim':{photo:'photos/seungjun-kim.jpg',bio:"Associate Professor at the KDI School of Public Policy and Management. His research explores international political economy, foreign direct investment, industrial policy, and geo-economic statecraft."}
};
const sessions=[
 {time:'09:00–09:10',kind:'Opening',title:'Welcome and Opening Remarks',people:[{role:'Welcome',name:'Beom-Shik Shin',affiliation:'SNU'}]},
 {time:'09:10–09:40',kind:'Keynote',title:'Keynote Address',people:[{role:'Keynote speaker',name:'Kyung-Sup Chang',affiliation:'SNU',title:'Asia in Asianization: 21st Century Trends in Transnational Societization'}]},
 {time:'09:40–11:10',kind:'Session 1',title:'Connectivity and the Challenges to the Liberal Script',description:'A conceptual framing of connectivity as a constitutive condition for resilience across geopolitical, societal, and technological dimensions.',people:[{role:'Moderator',name:'Diana Panke',affiliation:'SCRIPTS'},{role:'Speaker',name:'Tanja A. Börzel',affiliation:'SCRIPTS',title:'Connectivity, Contestation and Resilience of the Liberal Script'},{role:'Speaker',name:'Jeong-Woo Koo',affiliation:'Sungkyunkwan',title:'Organizational Connectivity and the Resilience of the Liberal Script: Institutional Investors, Human Rights Policies, and Due Diligence'},{role:'Speaker',name:'Yasemin Soysal',affiliation:'SCRIPTS',title:'Connectivity Beyond the State: Levels, Carriers, and the Limits of Resilience'},{role:'Discussant',name:'Dong-Kyun Im',affiliation:'SNU'}]},
 {time:'11:10–11:30',kind:'Break',title:'Coffee Break',type:'break'},
 {time:'11:30–13:00',kind:'Session 2',title:'Geo-Political and Geo-Economic Connectivity: Entanglements, Vulnerabilities, and the Liberal Script',description:'Trade patterns, financial linkages, the Belt and Road Initiative, and strategic alignments and their effects on liberal institutions.',people:[{role:'Moderator',name:'Jieun Kim',affiliation:'SNU'},{role:'Speaker',name:'Mark Hallerberg',affiliation:'SCRIPTS',title:'When and How Does Infrastructure Financing Enhance Authoritarian Governance?'},{role:'Speaker',name:'Chungshik Moon',affiliation:'Chung-Ang University',title:'Selective Decoupling, Not Systemic Fragmentation: Political Distance and Foreign Direct Investment in the United States'},{role:'Speaker',name:'Taesuh Cha',affiliation:'SNU',title:'The End of Swinging Inside? Connectivity, Vulnerability, and South Korea’s Strategic Reckoning in an Era of Great-Power Competition'},{role:'Speaker',name:'Soo Yeon Kim',affiliation:'University of British Columbia',title:'Rescripting the Liberal Order? The AIIB and the Politics of Infrastructure Finance'},{role:'Discussant',name:'Brandon Ives',affiliation:'SNU'}]},
 {time:'13:00–14:30',kind:'Break',title:'Lunch Break',type:'break'},
 {time:'14:30–16:00',kind:'Session 3',title:'Societal Connectivity: Migration, Cohesion, and the Liberal Script',description:'Migration, gender, collective identities, belonging, and implications for the liberal script.',people:[{role:'Moderator',name:'Yoonsun Han',affiliation:'SNU'},{role:'Speaker',name:'Gülay Çağlar',affiliation:'SCRIPTS',title:'The Promise of Gender Equality: Connectivity, Normative Tensions, and the Resilience of the Liberal Script'},{role:'Speaker',name:'Inbok Rhee',affiliation:'Yonsei University',title:'Moderating Antifeminism: Evidence From a Survey Experiment in South Korea'},{role:'Speaker',name:'Min Hee Go',affiliation:'Ewha Womans University',title:'The Emotional Architecture of Social Disconnection: Threat Perceptions and Outgroup Animosity in South Korea'},{role:'Discussant',name:'Sung Eun Kim',affiliation:'Korea University'}]},
 {time:'16:00–16:20',kind:'Break',title:'Coffee Break',type:'break'},
 {time:'16:20–17:50',kind:'Session 4',title:'Technological Connectivity: Digital Infrastructures, Innovation Networks, and Weaponized Interdependence',description:'Digital infrastructures, technological exchanges, and pressures on open markets and liberal institutions.',people:[{role:'Moderator',name:'Joonseok Yang',affiliation:'Yonsei University'},{role:'Speaker',name:'Genia Kostka',affiliation:'SCRIPTS',title:'AI between Openness and Control: The Blurring of Liberal and Authoritarian Scripts'},{role:'Speaker',name:'ByungKoo Kim',affiliation:'KDI',title:'Barking Dogs Never Bite? Exit Options, Crisis Escalation, and the Onset of Trade Sanctions'},{role:'Speaker',name:'One-Sun Cho',affiliation:'STEPI',title:'Two Logics of Connectivity in the Submarine Cable Network: Who Excludes, Who Entangles, and Why'},{role:'Discussant',name:'Seungjun Kim',affiliation:'KDI'}]},
 {time:'17:50–19:00',kind:'Closing',title:'Closing Session / Workshop Dinner / Informal Networking',type:'break'}];
const make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;};
const portrait=p=>{const data=people[p.name]||{};if(data.photo){const img=make('img','portrait');img.src=data.photo;img.alt='Portrait of '+p.name;img.loading='lazy';return img;}return make('span','portrait-placeholder');};
const schedule=document.querySelector('#schedule-list');sessions.forEach(s=>{const a=make('article','schedule-item '+(s.type==='break'?'break':''));a.append(make('time','',s.time));const heading=make('div');heading.append(make('span','schedule-kind',s.kind),make('h3','',s.title));a.append(heading);const detail=make('div','schedule-detail');if(s.description)detail.append(make('p','',s.description));const list=make('div','schedule-people');(s.people||[]).forEach(p=>{const line=make('div','person-line');line.append(make('b','',p.role));const info=make('span','',p.name+' · '+p.affiliation);if(p.title)info.append(make('em','',p.title));line.append(info);list.append(line);});detail.append(list);a.append(detail);schedule.append(a);});
const groups=[{label:'Keynote',title:'Keynote Address',people:sessions[1].people}].concat(sessions.filter(s=>s.kind.indexOf('Session')===0).map(s=>({label:s.kind,title:s.title,people:s.people})));const target=document.querySelector('#participant-groups');
groups.forEach((g,i)=>{const section=make('section','participant-session'),head=make('div','participant-session-head');head.append(make('span','',String(i+1).padStart(2,'0')),make('h3','',g.title));section.append(head);[['Keynote speaker',p=>p.role==='Keynote speaker','participant-grid--keynote'],['Moderator & Discussant',p=>p.role==='Moderator'||p.role==='Discussant','participant-grid--support'],['Speakers',p=>p.role==='Speaker','']].forEach(([label,filter,cls])=>{const list=g.people.filter(filter);if(!list.length)return;const block=make('section','role-block'),grid=make('div','participant-grid '+cls);block.append(make('p','role-label',label));list.forEach(p=>{const b=make('button','participant-card');b.type='button';b.dataset.person=p.name;b.dataset.group=g.label;b.append(portrait(p),make('h4','',p.name),make('p','',p.affiliation),make('p','card-role',p.role));grid.append(b);});block.append(grid);section.append(block);});target.append(section);});
const dialog=document.querySelector('#participant-dialog'),nameEl=document.querySelector('#dialog-name'),roleEl=document.querySelector('#dialog-role'),affilEl=document.querySelector('#dialog-affiliation'),presentation=document.querySelector('#dialog-presentation'),photoEl=document.querySelector('#dialog-photo'),bioEl=document.querySelector('#dialog-bio-text');
document.addEventListener('click',e=>{const b=e.target.closest('.participant-card');if(!b)return;const group=groups.find(g=>g.label===b.dataset.group),p=group.people.find(x=>x.name===b.dataset.person);nameEl.textContent=p.name;roleEl.textContent=p.role+' — '+group.label;affilEl.textContent=p.affiliation;photoEl.replaceChildren(portrait(p));photoEl.firstChild.classList.add('large');presentation.replaceChildren();if(p.role==='Speaker'){presentation.append(make('h3','', 'Presentation'),make('p','', '“'+p.title+'”'));presentation.hidden=false;}else presentation.hidden=true;bioEl.textContent=(people[p.name]||{}).bio||'Biography to be announced.';dialog.showModal();});
document.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});document.querySelectorAll('[data-registration-link]').forEach(a=>{a.href=REGISTRATION_FORM_URL;a.target='_blank';a.rel='noopener noreferrer';a.classList.remove('disabled');a.removeAttribute('aria-disabled');});
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.site-nav');toggle.onclick=()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));nav.classList.toggle('is-open',!open);};document.querySelectorAll('.nav-trigger').forEach(t=>t.onclick=()=>{const g=t.closest('.nav-group'),open=g.classList.toggle('open');t.setAttribute('aria-expanded',String(open));});
